--liquibase formatted sql
--changeset mbakhoff:20240712-init
              
CREATE SEQUENCE "ACCOUNT_SEQ" START WITH 1 INCREMENT BY 50;           
CREATE SEQUENCE "PLAYLIST_CHANGE_SEQ" START WITH 1 INCREMENT BY 50;   
CREATE SEQUENCE "PLAYLIST_ITEM_SEQ" START WITH 1 INCREMENT BY 50;     
CREATE SEQUENCE "PLAYLIST_SEQ" START WITH 1 INCREMENT BY 50;          
CREATE SEQUENCE "PLAYLIST_SUBSCRIPTION_SEQ" START WITH 1 INCREMENT BY 50;             

CREATE TABLE "ACCOUNT"(
    "ID" BIGINT NOT NULL,
    "VERSION" BIGINT NOT NULL,
    "EMAIL" CHARACTER VARYING(255) NOT NULL,
    "NAME" CHARACTER VARYING(255) NOT NULL
);               
ALTER TABLE "ACCOUNT" ADD CONSTRAINT "PK_ACCOUNT" PRIMARY KEY("ID");
         
CREATE TABLE "PLAYLIST"(
    "ID" BIGINT NOT NULL,
    "LAST_CHANGE_ID" BIGINT,
    "LAST_UPDATE" TIMESTAMP(6) WITH TIME ZONE,
    "VERSION" BIGINT NOT NULL,
    "TITLE" CHARACTER VARYING(255),
    "YOUTUBE_ID" CHARACTER VARYING(255) NOT NULL
);            
ALTER TABLE "PLAYLIST" ADD CONSTRAINT "PK_PLAYLIST" PRIMARY KEY("ID");

CREATE TABLE "PLAYLIST_CHANGE"(
    "CREATED_AT" TIMESTAMP(6) WITH TIME ZONE NOT NULL,
    "ID" BIGINT NOT NULL,
    "PLAYLIST_ID" BIGINT NOT NULL,
    "NEW_TITLE" CHARACTER VARYING(255),
    "OLD_TITLE" CHARACTER VARYING(255),
    "YOUTUBE_ID" CHARACTER VARYING(255) NOT NULL
);   
ALTER TABLE "PLAYLIST_CHANGE" ADD CONSTRAINT "PK_PLAYLIST_CHANGE" PRIMARY KEY("ID");

CREATE TABLE "PLAYLIST_ITEM"(
    "ID" BIGINT NOT NULL,
    "PLAYLIST_ID" BIGINT NOT NULL,
    "VERSION" BIGINT NOT NULL,
    "TITLE" CHARACTER VARYING(255) NOT NULL,
    "YOUTUBE_ID" CHARACTER VARYING(255) NOT NULL
);         
ALTER TABLE "PLAYLIST_ITEM" ADD CONSTRAINT "PK_PLAYLIST_ITEM" PRIMARY KEY("ID");

CREATE TABLE "PLAYLIST_SUBSCRIPTION"(
    "ACCOUNT_ID" BIGINT NOT NULL,
    "ID" BIGINT NOT NULL,
    "LAST_CHANGE" BIGINT NOT NULL,
    "PLAYLIST_ID" BIGINT NOT NULL,
    "VERSION" BIGINT NOT NULL
);           
ALTER TABLE "PLAYLIST_SUBSCRIPTION" ADD CONSTRAINT "PK_PLAYLIST_SUBSCRIPTION" PRIMARY KEY("ID");

ALTER TABLE "PLAYLIST_SUBSCRIPTION" ADD CONSTRAINT "U_PLAYLIST_SUBSCRIPTION" UNIQUE("PLAYLIST_ID", "ACCOUNT_ID");
ALTER TABLE "PLAYLIST_CHANGE" ADD CONSTRAINT "FK_PLAYLIST_CHANGE_PLAYLIST_ID" FOREIGN KEY("PLAYLIST_ID") REFERENCES "PLAYLIST"("ID") ON DELETE CASCADE;
ALTER TABLE "PLAYLIST_SUBSCRIPTION" ADD CONSTRAINT "FK_PLAYLIST_SUBSCRIPTION_PLAYLIST_ID" FOREIGN KEY("PLAYLIST_ID") REFERENCES "PLAYLIST"("ID");
ALTER TABLE "PLAYLIST_SUBSCRIPTION" ADD CONSTRAINT "FK_PLAYLIST_SUBSCRIPTION_ACCOUNT_ID" FOREIGN KEY("ACCOUNT_ID") REFERENCES "ACCOUNT"("ID");
ALTER TABLE "PLAYLIST_ITEM" ADD CONSTRAINT "FK_PLAYLIST_ITEM_PLAYLIST_ID" FOREIGN KEY("PLAYLIST_ID") REFERENCES "PLAYLIST"("ID")  ON DELETE CASCADE;
ALTER TABLE "PLAYLIST" ADD CONSTRAINT "FK_PLAYLIST_LAST_CHANGE_ID" FOREIGN KEY("LAST_CHANGE_ID") REFERENCES "PLAYLIST_CHANGE"("ID") ON DELETE SET NULL;
