<html>
<body>
  <h1>Playlists have changed</h1>
  <#list playlistChanges as playlistChange>
    <h2>
      <a href="https://www.youtube.com/playlist?list=${playlistChange.playlist.youtubeId}">
        ${playlistChange.playlist.title?html}
      </a>
    </h2>
    <ol>
      <#list playlistChange.itemChanges as item>
        <#if item.newTitle??>
          <li>
            Renamed <a href="https://www.youtube.com/watch?v=${item.playlistItem}">${item.oldTitle?html}</a>
            <br/>
            New name is ${item.newTitle?html}
          </li>
        <#else>
          <li>
            Deleted <a href="https://www.youtube.com/watch?v=${item.playlistItem}">${item.oldTitle?html}</a>
          </li>
        </#if>
      </#list>
    </ol>
  </#list>
  <p>Generated by <a href="https://playlists.sigil.red">playlists.sigil.red</a></p>
</body>
</html>
